# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketracker', '0004_pokemon_caught'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='numCandies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='numInBag',
            field=models.IntegerField(default=0),
        ),
    ]
