# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketracker', '0010_auto_20180403_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='candyType',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poketracker.Pokemon'),
        ),
    ]
