# Generated by Django 2.0.4 on 2018-04-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketracker', '0011_auto_20180403_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candy',
            old_name='candyType',
            new_name='candy_type',
        ),
        migrations.RenameField(
            model_name='candy',
            old_name='numCandies',
            new_name='num_candies',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='candiesToEvolve',
            new_name='candies_to_evolve',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='numInBag',
            new_name='num_in_bag',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='baseEvolution',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolvesFrom',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_evolution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_evolution2', to='poketracker.Pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolves_from2', to='poketracker.Pokemon'),
        ),
    ]
