# Generated by Django 2.0.6 on 2018-06-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candy',
            options={'ordering': ['id'], 'verbose_name_plural': 'Candies'},
        ),
        migrations.RenameField(
            model_name='candy',
            old_name='candy_type',
            new_name='base_pokemon_type',
        ),
        migrations.RenameField(
            model_name='candy',
            old_name='num_candies',
            new_name='num_owned',
        ),
    ]
