# Generated by Django 2.0.6 on 2018-06-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['id'], 'verbose_name_plural': 'Pokemon'},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='base_evolution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolutionary_tree', to='pokemon.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolves_into', to='pokemon.Pokemon'),
        ),
    ]
