# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketracker', '0005_auto_20180315_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolvesFromName',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolvesFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketracker.Pokemon'),
        ),
    ]
