# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketracker', '0009_auto_20180323_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCandies', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='numCandies',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='baseEvolution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseEvolution2', to='poketracker.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolvesFrom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolvesFrom2', to='poketracker.Pokemon'),
        ),
        migrations.AddField(
            model_name='candy',
            name='candyType',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poketracker.Pokemon'),
        ),
    ]
